// +build !ignore_autogenerated

/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IronicClusterProviderSpec) DeepCopyInto(out *IronicClusterProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IronicClusterProviderSpec.
func (in *IronicClusterProviderSpec) DeepCopy() *IronicClusterProviderSpec {
	if in == nil {
		return nil
	}
	out := new(IronicClusterProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IronicClusterProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IronicClusterProviderSpecList) DeepCopyInto(out *IronicClusterProviderSpecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IronicClusterProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IronicClusterProviderSpecList.
func (in *IronicClusterProviderSpecList) DeepCopy() *IronicClusterProviderSpecList {
	if in == nil {
		return nil
	}
	out := new(IronicClusterProviderSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IronicClusterProviderSpecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IronicClusterProviderSpecSpec) DeepCopyInto(out *IronicClusterProviderSpecSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IronicClusterProviderSpecSpec.
func (in *IronicClusterProviderSpecSpec) DeepCopy() *IronicClusterProviderSpecSpec {
	if in == nil {
		return nil
	}
	out := new(IronicClusterProviderSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IronicClusterProviderSpecStatus) DeepCopyInto(out *IronicClusterProviderSpecStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IronicClusterProviderSpecStatus.
func (in *IronicClusterProviderSpecStatus) DeepCopy() *IronicClusterProviderSpecStatus {
	if in == nil {
		return nil
	}
	out := new(IronicClusterProviderSpecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IronicClusterProviderStatus) DeepCopyInto(out *IronicClusterProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IronicClusterProviderStatus.
func (in *IronicClusterProviderStatus) DeepCopy() *IronicClusterProviderStatus {
	if in == nil {
		return nil
	}
	out := new(IronicClusterProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IronicClusterProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IronicClusterProviderStatusList) DeepCopyInto(out *IronicClusterProviderStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IronicClusterProviderStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IronicClusterProviderStatusList.
func (in *IronicClusterProviderStatusList) DeepCopy() *IronicClusterProviderStatusList {
	if in == nil {
		return nil
	}
	out := new(IronicClusterProviderStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IronicClusterProviderStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IronicClusterProviderStatusSpec) DeepCopyInto(out *IronicClusterProviderStatusSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IronicClusterProviderStatusSpec.
func (in *IronicClusterProviderStatusSpec) DeepCopy() *IronicClusterProviderStatusSpec {
	if in == nil {
		return nil
	}
	out := new(IronicClusterProviderStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IronicClusterProviderStatusStatus) DeepCopyInto(out *IronicClusterProviderStatusStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IronicClusterProviderStatusStatus.
func (in *IronicClusterProviderStatusStatus) DeepCopy() *IronicClusterProviderStatusStatus {
	if in == nil {
		return nil
	}
	out := new(IronicClusterProviderStatusStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IronicMachineProviderSpec) DeepCopyInto(out *IronicMachineProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IronicMachineProviderSpec.
func (in *IronicMachineProviderSpec) DeepCopy() *IronicMachineProviderSpec {
	if in == nil {
		return nil
	}
	out := new(IronicMachineProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IronicMachineProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IronicMachineProviderSpecList) DeepCopyInto(out *IronicMachineProviderSpecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IronicMachineProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IronicMachineProviderSpecList.
func (in *IronicMachineProviderSpecList) DeepCopy() *IronicMachineProviderSpecList {
	if in == nil {
		return nil
	}
	out := new(IronicMachineProviderSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IronicMachineProviderSpecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IronicMachineProviderSpecSpec) DeepCopyInto(out *IronicMachineProviderSpecSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IronicMachineProviderSpecSpec.
func (in *IronicMachineProviderSpecSpec) DeepCopy() *IronicMachineProviderSpecSpec {
	if in == nil {
		return nil
	}
	out := new(IronicMachineProviderSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IronicMachineProviderSpecStatus) DeepCopyInto(out *IronicMachineProviderSpecStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IronicMachineProviderSpecStatus.
func (in *IronicMachineProviderSpecStatus) DeepCopy() *IronicMachineProviderSpecStatus {
	if in == nil {
		return nil
	}
	out := new(IronicMachineProviderSpecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IronicMachineProviderStatus) DeepCopyInto(out *IronicMachineProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IronicMachineProviderStatus.
func (in *IronicMachineProviderStatus) DeepCopy() *IronicMachineProviderStatus {
	if in == nil {
		return nil
	}
	out := new(IronicMachineProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IronicMachineProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IronicMachineProviderStatusList) DeepCopyInto(out *IronicMachineProviderStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IronicMachineProviderStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IronicMachineProviderStatusList.
func (in *IronicMachineProviderStatusList) DeepCopy() *IronicMachineProviderStatusList {
	if in == nil {
		return nil
	}
	out := new(IronicMachineProviderStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IronicMachineProviderStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IronicMachineProviderStatusSpec) DeepCopyInto(out *IronicMachineProviderStatusSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IronicMachineProviderStatusSpec.
func (in *IronicMachineProviderStatusSpec) DeepCopy() *IronicMachineProviderStatusSpec {
	if in == nil {
		return nil
	}
	out := new(IronicMachineProviderStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IronicMachineProviderStatusStatus) DeepCopyInto(out *IronicMachineProviderStatusStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IronicMachineProviderStatusStatus.
func (in *IronicMachineProviderStatusStatus) DeepCopy() *IronicMachineProviderStatusStatus {
	if in == nil {
		return nil
	}
	out := new(IronicMachineProviderStatusStatus)
	in.DeepCopyInto(out)
	return out
}
