apiVersion: ironic.cluster.k8s.io/v1alpha1
kind: IronicMachineProviderStatus
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ironicmachineproviderstatus-sample
spec:
  # Add fields here
  foo: bar
